service_instance_id: "1"
kafka_servers: ["kafka:9092"]
mongo_dsn: mongodb://localhost:27017
db_name: rs
mongo_timeout: 300
uos_auth_config:
  auth_key: "{}"
  auth_check_claims: {}
alt_accessions_collection: alt_accessions
alt_accessions_topic: alt-accessions
