[project]
name = "rs"
version = "2.0.0"
description = "GHGA Registry Service - a service for ingesting and archiving metadata from data submitters."
dependencies = [
    "typer >= 0.25",
    "ghga-service-commons[api,auth] >= 7.0",
    "ghga-event-schemas ~= 13.0",
    "hexkit[akafka,mongodb,opentelemetry] >= 8.2",
]

[project.urls]
Repository = "https://github.com/ghga-de/ghga-registry-service"

[project.scripts]
rs = "rs.__main__:cli"
